name = "d3d_registry"
uuid = "6a8b0731-4b1f-4ca5-95d6-a5e67c3c59ec"
repo = "https://github.com/DIII-D/D3DRegistry.jl"
description = "Julia registry for DIII-D"

[packages]
50b852fb-755b-4f1c-b4e6-649ec8fe8475 = { name = "FusionSpecies", path = "F/FusionSpecies" }
